<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.MTP">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="AngleSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dfe.Acec.Web\Dfe.Acec.Web.csproj" />
  </ItemGroup>

</Project>
