sonar.projectKey=DFE-Digital_accessing-childcare-entitlement-checker
sonar.organization=dfe-digital
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests

sonar.exclusions=**/bin/**,**/obj/**,**/*.html,**/*.css,**/*.scss,**/wwwroot/**
sonar.coverage.exclusions=**/Program.cs

sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml