env:
  contexts:
    - name: Application
      urls:
        - ${TARGET_URL}
      includePaths:
        - ${TARGET_URL}.*
jobs:
  - type: alertFilter
    name: "Ignore False Positives and Informational alerts"
    alertFilters:
      - ruleId: 10112
        newRisk: "False Positive"
        context: Application
        parameter: ".AspNetCore.Session"
      - ruleId: 10109
        newRisk: "False Positive"
        context: Application

  - type: script
    parameters:
      action: add
      type: httpsender
      name: auth-header
      engine: ECMAScript
      file: /zap/wrk/zap/auth-header.js

  - type: spider
    parameters:
      context: Application
      maxDuration: 20

  - type: passiveScan-wait

  - type: activeScan
    parameters:
      context: Application
      maxScanDurationInMins: 60

  - type: report
    parameters:
      template: traditional-md
      reportDir: /zap/wrk/zap
      reportFile: zap-report.md

  - type: report
    parameters:
      template: sarif-json
      reportDir: /zap/wrk/zap
      reportFile: zap-results.sarif.json