name: Build Infrastructure

on:
  workflow_call:
    inputs:
      infra-directory:
        required: true
        type: string
        default: "infra"

      publish:
        required: false
        type: boolean
        default: false

jobs:
  infrastructure:
    name: CI checks
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      CHECKOV_RESULTS: checkov-results
    permissions:
      contents: read
      checks: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION || '1.9.8' }}

      - name: Generate build metadata
        env:
          G_SHA: ${{ github.sha }}
          G_REF: ${{ github.ref_name }}
          G_RUN_ID: ${{ github.run_id }}
        run: |
          TERRAFORM_VERSION=$(terraform version -json | jq -r .terraform_version)
          
          jq -n \
            --arg commit "$G_SHA" \
            --arg branch "$G_REF" \
            --arg buildDate "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            --arg terraform "$TERRAFORM_VERSION" \
            --arg runId "$G_RUN_ID" \
            '{commit: $commit, branch: $branch, buildDate: $buildDate, terraform: $terraform, runId: $runId}' \
            > build-infra-metadata.json

      - name: Terraform Init
        run: terraform init -input=false -backend=false
        working-directory: ${{ inputs.infra-directory }}/terraform

      - name: Terraform Format check
        id: fmt
        run: terraform fmt -check
        working-directory: ${{ inputs.infra-directory }}/terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ${{ inputs.infra-directory }}/terraform

      - name: Pull Checkov image
        run: docker pull bridgecrew/checkov

      - name: Run Checkov scan
        id: checkov
        env:
          WORKSPACE: ${{ github.workspace }}
          TF_DIR: ${{ inputs.infra-directory }}/terraform
        run: |
          mkdir -p "$WORKSPACE/$CHECKOV_RESULTS"
          
          docker run --rm \
            -v "$WORKSPACE/$TF_DIR:/tf" \
            -v "$WORKSPACE/$CHECKOV_RESULTS:/results" \
            -v "$WORKSPACE/$TF_DIR/environments:/env" \
            ghcr.io/dfe-digital/dfe-checkov-policies/checkov-elz:ELZ-2026.07.1 \
            -d /tf --var-file "/env/production.tfvars" \
            -o cli \
            -o junitxml \
            --output-file-path console,/results/results.xml

      - name: Publish Checkov results
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2
        if: always()
        with:
          name: Checkov Scan Results
          path: ${{ github.workspace }}/${{ env.CHECKOV_RESULTS }}/results.xml
          reporter: java-junit
          fail-on-error: true

      - name: Upload metadata
        uses: actions/upload-artifact@v7
        with:
          name: build-infra-metadata
          path: build-infra-metadata.json

      - name: Create infrastructure package
        if: inputs.publish
        working-directory: ${{ inputs.infra-directory }}
        run: |
          zip -r infra-package.zip .

      - name: Upload infra package
        if: inputs.publish
        uses: actions/upload-artifact@v7
        with:
          name: infra-package
          path: ${{ inputs.infra-directory }}/infra-package.zip
