name: Build Shutter

on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        default: false

jobs:
  shutter:
    name: Package Shutter Content
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install dependencies and compile assets
        if: inputs.publish
        run: |
          cd src/Dfe.Acec.Shutter
          npm ci
          npm run build

      - name: Zip Shutter Content
        if: inputs.publish
        run: |
          cd src/Dfe.Acec.Shutter
          zip -r ../../shutter-content.zip index.html assets

      - name: Upload Shutter Content Artifact
        if: inputs.publish
        uses: actions/upload-artifact@v7
        with:
          name: shutter-content
          path: shutter-content.zip
