name: Build Terraform

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        default: "infra/terraform"

      terraform-version:
        required: false
        type: string
        default: "1.9.8"

      create-package:
        required: false
        type: boolean
        default: false

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Terraform Init
        run: terraform init -input=false -backend=false

      - name: Terraform Format Check
        run: terraform fmt #-check

      - name: Terraform Validate
        run: terraform validate

      - name: Pull Checkov image
        run: docker pull bridgecrew/checkov

      - name: Run Checkov scan
        run: |
          docker run --rm \
            --volume "${{ github.workspace }}/${{ inputs.working-directory }}:/tf" \
            bridgecrew/checkov:latest \
            -d /tf \
            -o cli \
            -o sarif \
            --output-file-path console,/tf/results.sarif \
            --soft-fail

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: ${{ github.workspace }}/${{ inputs.working-directory }}/results.sarif

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: checkov-results
          path: ${{ github.workspace }}/${{ inputs.working-directory }}/results.sarif

      - name: Create Terraform Package
        if: inputs.create-package
        run: |
          zip -r terraform-package.zip .

      - name: Upload Terraform Package
        if: inputs.create-package
        uses: actions/upload-artifact@v7
        with:
          name: terraform-package-${{ github.sha }}
          path: ${{ inputs.working-directory }}/terraform-package.zip