name: CI

on:
  workflow_call:
#  workflow_dispatch:
#    inputs:
#      progressToTestDeployment:
#        description: 'Deploy to test, staging, and production environments'
#        required: false
#        type: boolean
#        default: false
#  push:
#    branches:
#      - main
#    paths-ignore:
#      - docs/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit

  e2e-tests:
    name: Tests (E2E)
    needs: build-and-test
    uses: ./.github/workflows/e2e-tests.yml

  deploy-dev:
    name: Deploy
    needs: build-and-test
    if: (github.event_name == 'push' && github.ref_name == 'main') || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/infra-deploy.yml
    with:
      environment: development
    secrets: inherit

  deploy-test:
    name: 'Deploy to Test'
    needs: deploy-dev
    if: inputs.progressToTestDeployment == true
    uses: ./.github/workflows/infra-deploy.yml
    with:
      environment: test
    secrets: inherit

  deploy-staging:
    name: 'Deploy to Staging'
    needs: deploy-test
    if: inputs.progressToTestDeployment == true
    uses: ./.github/workflows/infra-deploy.yml
    with:
      environment: staging
    secrets: inherit

  # STAGE 4: DEPLOY TO PRODUCTION 
  # (todo: bring it back later when production subscription is ready,this is commented just to be very safe with prod)
#   deploy-production:
#     name: 'Deploy to Production'
#     needs: deploy-staging
#     if: inputs.progressToTestDeployment == true
#     uses: ./.github/workflows/infra-deploy.yml
#     with:
#       environment: production
#     secrets: inherit