name: CI

on:
  workflow_dispatch:
    inputs:
      deploy_to_test:
        description: 'Auto-deploy to Test environment?'
        type: boolean
        default: false
  # push: potentially clean this as we have manual trigger above
  #   branches:
  #     - main
  #     - 'feature/ac-501*'
  #   paths-ignore:
  #     - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # This modular approach assumes build-and-test.yml and e2e-tests.yml exist in .github/workflows
  build-and-test:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit

  e2e-tests:
    name: Tests (E2E)
    needs: build-and-test
    uses: ./.github/workflows/e2e-tests.yml

  deploy:
    name: Deploy
    needs: build-and-test
    # todo: check the 2nd condition logic to push to dev environment
    if: |
      (github.event_name == 'push' && github.ref_name == 'main') ||
      (github.event_name == 'pull_request' && github.head_ref == 'feature/ac-501_deploy-to-test' && github.event.inputs.deploy_to_test != 'true')
    uses: ./.github/workflows/infra-deploy.yml
    with:
      environment: development
    secrets: inherit

  promote:
    name: Promote to Higher Env
    needs: build-and-test
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_to_test == 'true'
    uses: ./.github/workflows/promote-to-higher-environment.yml
    with:
      environment: test
      run-id: ${{ github.run_id }}
    secrets: inherit