name: PR Validation

on:
  #pull_request:
  push:
    branches:
      - chore/refactor-workflows

jobs:
  validate-dotnet:
    uses: ./.github/workflows/build-dotnet.yml
    permissions:
      contents: read
      checks: write
      pull-requests: read
    with:
      publish: false
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  validate-tf:
    uses: ./.github/workflows/build-terraform.yml
    with:
      working-directory: src/infrastructure/terraform