name: 'Release Orchestration (Test -> Prod)'

on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

jobs:

  deploy-test:
    name: 'Deploy to Test'
    if: github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run'
    uses: ./.github/workflows/infra-deploy.yml
    with:
      environment: test
      run-id: ${{ github.event.workflow_run.id }}
    secrets: inherit

 
  deploy-staging:
    name: 'Deploy to Staging'
    needs: deploy-test
    uses: ./.github/workflows/infra-deploy.yml
    with:
      environment: staging
      run-id: ${{ github.event.workflow_run.id }}
    secrets: inherit

  # STAGE 4: DEPLOY TO PRODUCTION (todo: bring it back later when production subscription is ready,this is commented just to be very safe with prod)

#   deploy-production:
#     name: 'Deploy to Production'
#     needs: deploy-staging
#     uses: ./.github/workflows/infra-deploy.yml
#     with:
#       environment: production
#       run-id: ${{ github.run_id }}
#     secrets: inherit