name: Main Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build-dotnet:
    name: Build Dotnet
    uses: ./.github/workflows/build-dotnet.yml
    with:
      publish: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-tf:
    name: Build Terraform
    uses: ./.github/workflows/build-terraform.yml
    with:
      terraform-directory: infra/terraform
      publish: true

  deploy-dev:
    name: Deploy Development
    needs: [build-dotnet, build-tf]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: development
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      DEVELOPMENT_BASIC_AUTH_PASSWORD: ${{ secrets.DEVELOPMENT_BASIC_AUTH_PASSWORD }}

  deploy-test:
    name: Deploy Test
    needs: [build-dotnet, build-tf]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: test
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      DEVELOPMENT_BASIC_AUTH_PASSWORD: ${{ secrets.DEVELOPMENT_BASIC_AUTH_PASSWORD }}

  e2e-tests:
    name: E2E Tests
    needs: [deploy-test]
    uses: ./.github/workflows/run-e2e-tests.yml
    with:
      SUT: ${{ needs.deploy-test.outputs.deploy_url }}
      environment: test
    secrets:
      DEVELOPMENT_BASIC_AUTH_PASSWORD: ${{ secrets.DEVELOPMENT_BASIC_AUTH_PASSWORD }}

  a11y-tests:
    name: A11y Tests
    runs-on: ubuntu-latest
    needs: [deploy-test]
    steps:
      - name: Run a11y tests
        run: |
          echo "Running a11y tests"
